services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "127.0.0.1:9100:9100"
    networks:
      - monitoring
    pid: "host"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    privileged: true
    cap_add:
    - SYS_ADMIN
    - DAC_READ_SEARCH
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro,Z
      #  === SELinux will HATE this ===
      # - /run/log/journal:/run/log/journal:ro
      - /var/log/journal:/var/log/journal:ro
    command:
      - "-config.file=/etc/promtail/config.yml"
    ports:
      - "127.0.0.1:9080:9080"
    networks:
      - monitoring
    depends_on:
      - loki
    restart: unless-stopped
